{% set name = "aimrocks" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aimhubio/aimrocks/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b63e7f8c596d410cf7623632535e7fa32a2dda228934a24e8ffd5299febba9a4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}               # [build_platform != target_platform]
    - cython ==3.0.*                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools >=25
    - cython ==3.0.*
    - rocksdb ==6.29.5
    # NOTE(hadim): we include those rocksdb compression libs since they are not included implicitely.
    - lz4-c
    - snappy
    - zstd
    - bzip2
    - zlib
  run:
    - python

test:
  imports:
    - aimrocks
  commands:
    - pip check
    - pytest -v tests/
  requires:
    - pip
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/aimhubio/aimrocks
  summary: "aimrocks — python/cython bindings for RocksDB."
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - gorarakelyan
