{% set name = "aimrocks" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # 0.3.1: waiting for a proper git tag
  url: https://github.com/aimhubio/aimrocks/archive/812f15af21b5e137159f8b5c620b7b6b65bee8b4.tar.gz
  sha256: b9289febb49ca31bec6300e8d71c2551b5b7781d6274471481733eb23d845f77
  # url: https://github.com/aimhubio/aimrocks/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: c30ff542ba95cd615616cec07061f33e8385ebd131801fc2cdaf83010241a469

  patches:
    - setup_rocksdb.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}               # [build_platform != target_platform]
    - cython ==3.0.*                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools >=25
    - cython ==3.0.*
    - rocksdb ==6.29.5
    # NOTE(hadim): we include those rocksdb compression libs since they are not included implicitely.
    - lz4-c
    - snappy
    - zstd
    - bzip2
    - zlib
  run:
    - python

test:
  imports:
    - aimrocks
  commands:
    - pip check
    - pytest -v tests/
  requires:
    - pip
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/aimhubio/aimrocks
  summary: "aimrocks — python/cython bindings for RocksDB."
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - gorarakelyan
